### ISSUE TITLE
Ethernet Port

### ISSUE THREAD

**Issue by weitieda** [sarkrui/Hackintosh-Z390-Aorus-Pro-9700K-RX580#4]
Hi Sark,

Thanks for sharing your build.

I have the same CPU and Motherboard. May I ask if I don't the Apple Wi-Fi card, I guess the ethernet port and bluetooth should still work? The BCM94360CD is just for enabling the Wi-Fi, right?

Thanks,
Tieda

**Comment by sarkrui** [comment]
Hi @weitieda,

The Z390 Aorus Pro ([not the Pro WIFI version](https://www.gigabyte.com/Motherboard/Z390-AORUS-PRO-WIFI-rev-10#kf)) doesn't come with a Bluetooth and Wi-Fi card. And yes, the on-board Ethernet will work with the ejection of `IntelMausi.kext`. With BCM94360CD (paired with an M.2 to 6+12 pin adapter), BT/Wi-Fi, AirDrop, as well as Handoff will work just fine. 

Yours
Sark
