### ISSUE TITLE
"OCABC Imcompatible OpenRuntime r10 , require r11"   on boot with your EFI Folder.

### ISSUE THREAD

**Issue by fjmatos** [sarkrui/Hackintosh-Z390-Aorus-Pro-9700K-RX580#7]
Hello, Sarkui.
I got almost the same hardware as you:  Gigabyte Aorus Z390 Pro,  i5-9600K , Shaphire  RX580 8GB, sabrent nvme 1TB, OC0.6
I´m trying to install hackintosh on this hardware but I´m having many issues.

I have tried with your EFI folder hoping it would work taking into account that the hardware is very similar, but on boot I get the following error : "OCABC Imcompatible OpenRuntime r10 , require r11"

I hope you could help me.
I greatly apreciate your assitance.

Did you got the same issue ?

Thank in advance.

**Comment by sarkrui** [comment]
> I have tried with your EFI folder hoping it would work taking into account that the hardware is very similar

I wonder if you copied the whole EFI (without any modification) to your EFI. It should work out just alright.

> OCABC Incompatible OpenRuntime r10 , require r11

It seemed you referenced OpenRuntime.efi in your config.plist but OpenCore bootloader can't find it. It could be because of incompatible version or invalid file name.

**Comment by fjmatos** [comment]
Thanks for your quick anwer.

I copied your whole EFI folder to the EFI boot disk. I just  changed  MLB, SerialNumber and systemuuid. So, I don´t know why the behavior is different.

**Comment by sarkrui** [comment]
Hi @fjmatos 
I just remove `CPUFriend` from the repository and update the release file as well. You can give a try. I don't really know what went wrong to be honest.

**Comment by ainsleyclark** [comment]
Ah great glad you got it sorted.
I think I left all of the tools enabled, but you can certainly remove them in plist.
