### ISSUE TITLE
AMD controller reference in config_UHD630_Only.plist

### ISSUE THREAD

**Issue by amarnaud2** [sarkrui/Hackintosh-Z390-Aorus-Pro-9700K-RX580#8]
Hello,

First I'dl like to thank you for your great work. I wanted to contact you but I didn't find another way than creating an issue. 

When I edit your config_UHD630_Only.plist file, I can find the following line: 
'<string>com.apple.kext.AMD9500Controller</string>' in a <dict></dict> element. 

Is it normal or is it a remainder of your config.plist file? 

Regards, Arnaud

**Comment by sarkrui** [comment]
Hi Aranaud,

Thanks for your kind notice, it's a remainder from the vega config. I've fixed it on the repository. 

Yours 
Sark
